# Generated by Django 5.1.1 on 2025-01-22 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offline", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="payment_recived",
            field=models.CharField(
                blank=True, default="Mr. V. Mustafa", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="branch",
            field=models.CharField(
                choices=[
                    ("CSE", "CSE"),
                    ("CAI", "CAI"),
                    ("CSD", "CSD"),
                    ("CSM", "CSM"),
                    ("CSN", "CSN"),
                    ("CSC", "CSC"),
                    ("CST", "CST"),
                    ("ECE", "ECE"),
                    ("EEE", "EEE"),
                    ("MECH", "MECH"),
                    ("CIVIL", "CIVIL"),
                    ("MBA", "MBA"),
                    ("MCA", "MCA"),
                    ("MTECH", "MTECH"),
                ],
                default="CSE",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="section",
            field=models.CharField(
                choices=[
                    ("A", "A"),
                    ("B", "B"),
                    ("C", "C"),
                    ("D", "D"),
                    ("E", "E"),
                    ("F", "F"),
                    ("G", "G"),
                    ("H", "H"),
                    ("I", "I"),
                    ("J", "J"),
                ],
                default="A",
                max_length=10,
            ),
        ),
    ]
