# Generated by Django 5.1.1 on 2025-01-22 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offline", "0002_registration_payment_recived_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="year",
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)]),
        ),
    ]
