# Generated by Django 5.0.6 on 2025-02-05 00:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offline', '0003_alter_registration_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='registration',
            name='registered_on',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='registration',
            name='year',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1),
        ),
    ]
