# Generated by Django 5.0.6 on 2025-02-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offline', '0006_alter_registration_email_head'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='head',
            options={},
        ),
        migrations.AlterModelManagers(
            name='head',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='head',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='head',
            name='email',
        ),
        migrations.RemoveField(
            model_name='head',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='head',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='head',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='head',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='head',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='head',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='head',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='head',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='head',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='head',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
